# Generated by Django 3.2.5 on 2022-08-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bachelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, default='', max_length=100)),
                ('nom', models.CharField(blank=True, default='', max_length=100)),
                ('prenom', models.CharField(blank=True, default='', max_length=100)),
                ('serie_bac', models.CharField(blank=True, default='', max_length=15)),
                ('annee_bac', models.IntegerField(default=2022)),
                ('lieu_naissance', models.CharField(blank=True, default='', max_length=100)),
                ('etablissement', models.CharField(blank=True, default='', max_length=100)),
                ('moyenne_bac', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
