# Generated by Django 3.2.5 on 2022-08-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orientationSystem', '0002_auto_20220820_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bachelier',
            old_name='annee_bac',
            new_name='wilaya_bac',
        ),
    ]
