# Generated by Django 3.2.5 on 2022-08-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orientationSystem', '0003_rename_annee_bac_bachelier_wilaya_bac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bachelier',
            name='wilaya_bac',
            field=models.CharField(default=16, max_length=2),
        ),
    ]
